#!/usr/bin/python

# just modify the code in https://docs.python.org/2/library/socketserver.html.
import SocketServer
import socket

HOSTNAME = socket.gethostname()
HOST = socket.gethostbyname(HOSTNAME)

class MyUDPHandler(SocketServer.BaseRequestHandler):
    """
    This class works similar to the TCP handler class, except that
    self.request consists of a pair of data and client socket, and since
    there is no connection the client address must be given explicitly
    when sending data back via sendto().
    """

    def handle(self):
        data = self.request[0].strip()
        socket = self.request[1]
        #print "{} wrote:".format(self.client_address[0])
        #print data
        if data == "someonethere":
          socket.sendto(HOSTNAME +": "+ HOST+'\n', self.client_address)

if __name__ == "__main__":
    PORT = 8613
    server = SocketServer.UDPServer(('', PORT), MyUDPHandler)
    server.serve_forever()
