#!/bin/sh

set -e

case "$1" in
    configure)
       codename=`lsb_release -c | awk '{print $2}'`
       systemctl enable urs.service
       service urs start
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
